### ISSUE TITLE
Standalone mode support

### ISSUE THREAD

**Issue by endorama** [elastic/elastic-agent-gcp-kubernetes-app#4]
At the moment the template does not really support the standalone mode: is possible to configure the required variables (Kibana host, username and password) but [`FLEET_ENROLL` is always set to `1`](https://github.com/elastic/elastic-agent-gcp-kubernetes-app/blob/961a5fb05c8e38fb5269f00e1ab35f3bdea1f648/7.17.5/deployer/manifest/manifests.yaml.template#L27-L28)

We need to decide if this is something we want to support, at the moment the template used is the Fleet managed one (copied from https://github.com/elastic/elastic-agent/blob/9c0cb456bbf73dfc87159a97759611de0151fba1/deploy/kubernetes/elastic-agent-managed-kubernetes.yaml)

**Comment by endorama** [comment]
Asking @tommyers-elastic and @ravikesarwani for inputs here.

**Comment by ravikesarwani** [comment]
I would say let's focus the first deliverable on the fleet managed Agent. Standalone is an advanced case and we can take that up based on actual customer inputs.

**Comment by endorama** [comment]
Ok, so I'm going to remove standalone configuration variables, as they are confusing and untested.
